let names = ["Ajla ",
"Andreas Edin",
"Anna Börjesson",
"Anton A ",
"Anton Klock ",
"Björn",
"Calle",
"Camilla Björklund",
"Christian T",
"Daniel Tran",
"David Skoog",
"Ebba Hesslling",
"Elina Lundblad",
"Elina Lundström",
"Elisabeth Öman",
"Fanny Götesson",
"Felicia Svärd",
"Frederik Remmer",
"Frida Hofmann Kruse",
"Henrik Svärd",
"Ilker Akbas",
"Isabella Henschel",
"Jennifer Andersson",
"Jessica Jan 2021",
"Johan Hallberg",
"Johan Svärd",
"Johan Åberg",
"Jonatan Fagerlund",
"Louise Persson",
"Lovisa Tegner",
"Madde Zigg",
"Madelene Blomqvist",
"Marcus H",
"Mari Torstila",
"Martin Sohtell ",
"Martina Fagerborg",
"Mathilda Lindh",
"Mike LG",
"Michelle",
"Nathalie Karst",
"Oscar Gezelius",
"Patrik",
"Paulo Lising",
"Sara Fooladi",
"Shalaw Kasem",
"Simon Näsgårde",
"Taika Guttom",
"Timothy",
"Tom Nilsson",
"Yasamina Gulen",
"Zanna Wiede",
"Alexandar Pesic",
"Mikael Björk"]

export default names;