const names = ["Ajla ",
"Andreas Edin",
"Anna Börjesson",
"Anton A ",
"Anton Klock ",
"Camilla Björklund",
"Christian T",
"Daniel Tran",
"Ebba Hesslling",
"Elina Lundblad",
"Elina Lundström",
"Elisabeth Öman",
"Fanny Götesson",
"Felicia Svärd",
"Frederik Remmer",
"Frida Hofmann Kruse",
"Henrik Svärd",
"Ilker Akbas",
"Isabella Henschel",
"Jennifer Andersson",
"Jessica Jan 2021",
"Johan Hallberg",
"Johan Svärd",
"Johan Åberg",
"Jonatan Fagerlund",
"Louise Persson",
"Lovisa Tegner",
"Madde Zigg",
"Madelene Blomqvist",
"Marcus H",
"Mari Torstila",
"Martina Fagerborg",
"Mathilda Lindh",
"Mike LG",
"Michelle",
"Nathalie Karst",
"Oscar Gezelius",
"Paulo Lising",
"Sara Fooladi",
"Shalaw Kasem",
"Simon Näsgårde",
"Taika Guttom",
"Timothy",
"Yasamina Gulen",
"Zanna Wiede",
"Alexandar Pesic",
"Mikael Björk"]

const leads = [
    "Björn",
    "Calle",
    "David Skoog",
    "Patrik",
    "Tom Nilsson",
    "Martin Sohtell "
]

export {names, leads};